# ----
# Site

title: 徒 setto セット
description: Set, Party, Gang! &#35;Cybersoul

url: https://setto.basspistol.com
permalink: /:categories/:title/
mediaurl: https://media.basspistol.com/setto

# banner should be 1024x1024
banner: /assets/img/setto_logo.png
icon: /assets/img/setto_icon.png
logo: /assets/img/setto_icon.png


exclude:
  - changelog.md
  - '*.*~'
  - '*.xcf'
  - '*.blend*'
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

social:
  name: 徒 Setto セット
  links:
    - https://www.instagram.com/tosettosetto
    - https://twitter.com/ToSettoSetto

publisher:
  name: Basspistol
  domain: basspistol.com
  mail: info@basspistol.com

# musicbrainz
musicbrainz_artistid: '31e8e456-0589-47eb-9334-20872851cd3e'

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at

# GEO 

geo: 
  timezone: "Europe/Stockholm"
  lat: '7.48777'
  long: '2.076389'
  region: BJ-ZO
  town: Setto

# Defaults

collections:
  albums:
    output: true
    permalink: /albums/:name/
  tracks:
    output: true
    permalink: /albums/:path/
  authors:
    output: false

categories:
  - releases
  - rambling

exclude:
  - changelog.md
  - '*.*~'
  - '*.xcf'
  - '*.blend*'
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

sass:
  sass_dir: _sass

defaults:
  - scope:
      path: ""
    values:
      lang: en  
  - scope:
      path: ""
      type: "tracks"
    values:
      layout: "track"
      lang: en
      seo:
        type: "AudioObject"
  - scope:
      path: ""
      type: "albums"
    values:
      layout: "album"
      lang: en
      seo:
        type: "AudioObject"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      lang: en
      _options:
        image:
          width: 1024
          height: 720
          resize_style: cover
          uploads_dir: "/images/pages"
        content:
          width: 720
          height: 720
          resize_style: cover
          uploads_dir: "/images/pages"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: en
      permalink: /:title/
      _options:
        image:
          width: 1024
          height: 720
          resize_style: cover
          uploads_dir: "/images/posts"
        content:
          width: 720
          height: 720
          resize_style: cover
          uploads_dir: "/images/posts"  
# ---------
# Translate
lang: en