url: "https://setto.basspistol.com" # the base hostname & protocol for your site
permalink: /:categories/:title/

exclude:
  - changelog.md
  - '*.*~'
  - '*.xcf'
  - '*.blend*'
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

title : 徒 setto セット
description: 'Set, Party, Gang! &#35;Cybersoul.'
geo: 
  timezone: "Europe/Switzerland"
  lat: '46.203918'
  long: '6.133011'
  region: 'CH-GE'
  town: 'Geneva'
  country: 'Switzerland'
  postalcode: '1201'

banner:   /images/setto-logo.svg
icon:   /images/setto-logoicon.svg
logo:   /images/setto-logo.svg
logo-footer: /images/setto-logo-dark.svg
mediaurl: https://media.basspistol.com/setto.basspistol.com

publisher:
  name: To Setto Setto
  domain: setto.basspistol.com
  mail: setto@basspistol.com
social:
  name: To Setto Setto
  links:
    - https://twitter.com/ToSettoSetto
    - https://instagram.com/ToSettoSetto

categories:
  - releases
  - ramblings

collections:
  albums:
    output: false
    permalink: /albums/:name/
  tracks:
    output: true
    permalink: /albums/:path/
  authors:
    output: false
      
# defaults

sass:
  sass_dir: _sass

defaults:
  - scope:
      path: ""
    values:
      lang: en  
  - scope:
      path: ""
      type: "tracks"
    values:
      layout: "track"
      lang: en
      seo:
        type: "AudioObject"
  - scope:
      path: ""
      type: "albums"
    values:
      layout: "album"
      lang: en
      seo:
        type: "AudioObject"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      lang: en
      _options:
        image:
          width: 1024
          height: 720
          resize_style: cover
          uploads_dir: "/images/pages"
        content:
          width: 720
          height: 720
          resize_style: cover
          uploads_dir: "/images/pages"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: en
      permalink: /:title/
      _options:
        image:
          width: 1024
          height: 720
          resize_style: cover
          uploads_dir: "/images/posts"
        content:
          width: 720
          height: 720
          resize_style: cover
          uploads_dir: "/images/posts"  
# ---------
# Translate
lang: en
